### ISSUE TITLE
Running on all file saves

### ISSUE THREAD

**Issue by devinrhode2** [tshm/elm-doctest#5]
It'd be great if elm-doctest was run on all file saves, and that a user got feedback just like a regular elm compiler error. Don't know if it'd be better to tie in with elm-reactor or latch onto/plug into elm, but I think getting errors inline in one's editor would be the slickest.

**Comment by tshm** [comment]
I guess one can use a file-watcher script such as fsmonitor and such.
I think we should let user to choose whatever the tool that they want to use or already using.
I'll keep this issue open as I'm not sure.

**Comment by tshm** [comment]
release-0.2.0 takes care of watching now.

**Comment by devinrhode2** [comment]
Yay!
